services:
  - type: web
    name: tacit
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATA_DIR
        value: /var/data
    disk:
      name: tacit-data
      mountPath: /var/data
      sizeGB: 10
